In [1]:
import numpy as np

In [7]:
x = np.array([10,5,8])

In [8]:
print(x)

[10  5  8]


In [11]:
y = np.array([7,5,6])
print(y)

[7 5 6]


In [12]:
np.dot(x,y)

143

In [13]:
f = np.array([2,4,16])
print(f)

[ 2  4 16]


In [14]:
z = np.array([11,10,9])
print(z)

[11 10  9]


In [24]:
f.dot(z)

206

In [18]:
f@z

206

In [25]:
np.dot(f,z)

206

In [27]:
z[1]

10